import React, { Component } from "react";
import { MDBBtn, MDBCol, MDBContainer, MDBRow } from "mdbreact";

class Body extends Component {
    render () {
    return (
    <MDBContainer
        style={{ marginTop: '20px' }}
    >
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean nec porta risus. Vestibulum eu sem quis ex varius pharetra eu vitae ipsum. Curabitur vel luctus ligula. Phasellus ac ante massa. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse finibus rutrum rutrum. Proin vitae vestibulum eros. Donec convallis egestas quam at facilisis.

Aliquam ut sodales metus. Praesent nec mauris dapibus, pulvinar elit ut, scelerisque metus. Maecenas in lacinia velit, a ultricies enim. Sed eleifend sem non risus fermentum porttitor. Donec dolor metus, consequat quis auctor sit amet, aliquam ut ex. Curabitur ullamcorper, est vel porttitor semper, odio orci euismod lacus, sed luctus mauris diam eu felis. Nunc dictum sem nulla, vel elementum dui porttitor quis. Duis quis dui malesuada, malesuada ante et, lacinia leo.

Aliquam in odio sagittis, imperdiet neque sed, blandit quam. Pellentesque tristique, mauris et lobortis feugiat, purus arcu vulputate felis, a molestie est mi id tellus. Ut sit amet lorem feugiat, fermentum nibh dignissim, condimentum nisl. Cras ornare nisi a sapien feugiat congue. Curabitur convallis pharetra erat vel lacinia. Donec consequat velit et mauris varius molestie. Ut vehicula mi a ligula pellentesque, commodo dictum lectus varius. Vestibulum id pellentesque justo. Vestibulum mattis ultrices lectus, ac mattis mauris tempor nec. Phasellus vel bibendum urna. Duis nec sem id felis ultricies mollis. Curabitur mollis, sapien eget dignissim lobortis, leo est cursus nisl, quis tincidunt nunc odio non est. In facilisis, nunc posuere aliquam volutpat, nisi velit varius erat, vel fermentum felis est sit amet urna.

Morbi nec sem massa. Duis faucibus molestie erat id gravida. Sed sit amet dui ultrices, vehicula mauris sed, iaculis velit. Morbi a neque pharetra, egestas orci a, dignissim felis. Donec lobortis lorem nec imperdiet tempor. Fusce eu sapien id dui convallis fermentum. Curabitur fringilla sodales urna, ut porta elit scelerisque non. Suspendisse quis sem ac arcu pellentesque rhoncus. Quisque eget justo nec magna tincidunt consectetur ac scelerisque sem. Nam malesuada nisi eu enim sagittis egestas. Praesent ut sapien quis velit faucibus maximus.

Duis pharetra pulvinar ultricies. Suspendisse rutrum vestibulum neque, a porttitor lectus dictum et. Nunc finibus enim quis diam sodales, quis vestibulum risus fringilla. Nulla ultrices ligula tincidunt congue lacinia. Proin ut augue orci. Sed dapibus, tellus dapibus finibus condimentum, metus elit ornare ligula, et porta magna erat nec elit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas malesuada et dui a pharetra. Mauris ac vehicula augue, in tincidunt enim. Sed auctor porttitor turpis, ac tempus est gravida eu. Donec in nunc neque. Phasellus scelerisque libero ut felis viverra, ac finibus metus feugiat. Morbi posuere bibendum imperdiet. Pellentesque elementum, nunc quis tristique tincidunt, dolor tortor auctor velit, ac cursus eros ante non ex. Nam molestie mi suscipit congue placerat. Duis sagittis elit tortor, ac lobortis odio scelerisque ac.

Proin eget sapien non libero congue tempus. Curabitur a diam nibh. Etiam a cursus elit. Praesent viverra nunc a malesuada vulputate. Suspendisse ullamcorper malesuada finibus. Fusce eleifend sit amet sem in sagittis. Donec faucibus sed nisl vitae vestibulum. Etiam nec consectetur diam, a bibendum nibh. Fusce neque mauris, efficitur eget facilisis at, vulputate nec justo. Ut pretium quam sed quam efficitur ullamcorper. Cras ac fermentum orci, quis lacinia diam. Quisque diam nisi, tincidunt et felis id, aliquam sodales erat.

Suspendisse in gravida quam, quis varius lacus. Duis hendrerit augue velit, vitae lacinia urna mattis sed. Curabitur sollicitudin laoreet mauris in congue. Integer ultrices augue ac eros pharetra fringilla vitae sit amet lorem. Donec et lacinia nulla, nec faucibus diam. Phasellus interdum, augue ac porttitor fringilla, sapien lorem tempor turpis, feugiat pulvinar dui urna vitae orci. Curabitur id dolor tempus, fermentum massa ut, posuere orci. Pellentesque dictum turpis vel suscipit scelerisque. Vivamus semper sapien eros, at euismod ante elementum feugiat. Nam sapien nisl, volutpat id viverra quis, pulvinar at ante. Vivamus pellentesque, enim quis rutrum varius, nunc dui convallis purus, non maximus risus orci nec nisl. Vivamus convallis congue purus, a venenatis est finibus sed.

Mauris quis consequat ante. Sed iaculis nibh id sem imperdiet suscipit. Sed fermentum eleifend lorem, at ornare tortor gravida non. Donec aliquam mauris ligula, et dictum diam rutrum sit amet. In tincidunt, metus non interdum gravida, leo eros ultrices purus, a maximus dui mi vel dui. Integer rutrum elit ut tortor tempus maximus. Phasellus consequat eleifend nunc ac fringilla. Maecenas ac dictum eros. Proin vulputate laoreet dolor sed pulvinar. Nulla iaculis a purus sed luctus. Praesent vehicula erat a magna scelerisque, sed pulvinar ipsum luctus. Vestibulum in feugiat neque. Ut pellentesque ante nec tellus volutpat pretium. Quisque id tempor mi.

Phasellus scelerisque sapien turpis, finibus imperdiet nunc suscipit vel. Suspendisse non lectus in mi laoreet euismod. Fusce at elit nec ipsum consectetur fringilla. Nunc in ex finibus, pretium ex aliquam, tristique eros. Fusce eget fermentum nisi, a luctus tortor. Quisque gravida imperdiet lorem, vitae vestibulum lorem vestibulum ut. Vestibulum eu elit risus. Integer eu nulla fermentum, vestibulum velit id, finibus risus. Ut a odio consequat, scelerisque ligula at, dignissim arcu. Aenean interdum mauris tincidunt, feugiat tortor ac, fringilla risus. Vivamus id convallis massa. Pellentesque in justo vel justo egestas fringilla at vel turpis.

Mauris in eros quis est gravida fermentum. Sed in finibus elit. Aliquam faucibus interdum purus, nec hendrerit elit pretium at. Maecenas in euismod quam, sed tincidunt felis. Cras sodales vehicula turpis, nec semper mi tincidunt sit amet. Aliquam iaculis magna maximus nisl condimentum tempus. Nullam sed vulputate dui. Aliquam erat volutpat. 
rem ipsum dolor sit amet, consectetur adipiscing elit. Aenean nec porta risus. Vestibulum eu sem quis ex varius pharetra eu vitae ipsum. Curabitur vel luctus ligula. Phasellus ac ante massa. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse finibus rutrum rutrum. Proin vitae vestibulum eros. Donec convallis egestas quam at facilisis.

Aliquam ut sodales metus. Praesent nec mauris dapibus, pulvinar elit ut, scelerisque metus. Maecenas in lacinia velit, a ultricies enim. Sed eleifend sem non risus fermentum porttitor. Donec dolor metus, consequat quis auctor sit amet, aliquam ut ex. Curabitur ullamcorper, est vel porttitor semper, odio orci euismod lacus, sed luctus mauris diam eu felis. Nunc dictum sem nulla, vel elementum dui porttitor quis. Duis quis dui malesuada, malesuada ante et, lacinia leo.

Aliquam in odio sagittis, imperdiet neque sed, blandit quam. Pellentesque tristique, mauris et lobortis feugiat, purus arcu vulputate felis, a molestie est mi id tellus. Ut sit amet lorem feugiat, fermentum nibh dignissim, condimentum nisl. Cras ornare nisi a sapien feugiat congue. Curabitur convallis pharetra erat vel lacinia. Donec consequat velit et mauris varius molestie. Ut vehicula mi a ligula pellentesque, commodo dictum lectus varius. Vestibulum id pellentesque justo. Vestibulum mattis ultrices lectus, ac mattis mauris tempor nec. Phasellus vel bibendum urna. Duis nec sem id felis ultricies mollis. Curabitur mollis, sapien eget dignissim lobortis, leo est cursus nisl, quis tincidunt nunc odio non est. In facilisis, nunc posuere aliquam volutpat, nisi velit varius erat, vel fermentum felis est sit amet urna.

Morbi nec sem massa. Duis faucibus molestie erat id gravida. Sed sit amet dui ultrices, vehicula mauris sed, iaculis velit. Morbi a neque pharetra, egestas orci a, dignissim felis. Donec lobortis lorem nec imperdiet tempor. Fusce eu sapien id dui convallis fermentum. Curabitur fringilla sodales urna, ut porta elit scelerisque non. Suspendisse quis sem ac arcu pellentesque rhoncus. Quisque eget justo nec magna tincidunt consectetur ac scelerisque sem. Nam malesuada nisi eu enim sagittis egestas. Praesent ut sapien quis velit faucibus maximus.

Duis pharetra pulvinar ultricies. Suspendisse rutrum vestibulum neque, a porttitor lectus dictum et. Nunc finibus enim quis diam sodales, quis vestibulum risus fringilla. Nulla ultrices ligula tincidunt congue lacinia. Proin ut augue orci. Sed dapibus, tellus dapibus finibus condimentum, metus elit ornare ligula, et porta magna erat nec elit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas malesuada et dui a pharetra. Mauris ac vehicula augue, in tincidunt enim. Sed auctor porttitor turpis, ac tempus est gravida eu. Donec in nunc neque. Phasellus scelerisque libero ut felis viverra, ac finibus metus feugiat. Morbi posuere bibendum imperdiet. Pellentesque elementum, nunc quis tristique tincidunt, dolor tortor auctor velit, ac cursus eros ante non ex. Nam molestie mi suscipit congue placerat. Duis sagittis elit tortor, ac lobortis odio scelerisque ac.

Proin eget sapien non libero congue tempus. Curabitur a diam nibh. Etiam a cursus elit. Praesent viverra nunc a malesuada vulputate. Suspendisse ullamcorper malesuada finibus. Fusce eleifend sit amet sem in sagittis. Donec faucibus sed nisl vitae vestibulum. Etiam nec consectetur diam, a bibendum nibh. Fusce neque mauris, efficitur eget facilisis at, vulputate nec justo. Ut pretium quam sed quam efficitur ullamcorper. Cras ac fermentum orci, quis lacinia diam. Quisque diam nisi, tincidunt et felis id, aliquam sodales erat.

Suspendisse in gravida quam, quis varius lacus. Duis hendrerit augue velit, vitae lacinia urna mattis sed. Curabitur sollicitudin laoreet mauris in congue. Integer ultrices augue ac eros pharetra fringilla vitae sit amet lorem. Donec et lacinia nulla, nec faucibus diam. Phasellus interdum, augue ac porttitor fringilla, sapien lorem tempor turpis, feugiat pulvinar dui urna vitae orci. Curabitur id dolor tempus, fermentum massa ut, posuere orci. Pellentesque dictum turpis vel suscipit scelerisque. Vivamus semper sapien eros, at euismod ante elementum feugiat. Nam sapien nisl, volutpat id viverra quis, pulvinar at ante. Vivamus pellentesque, enim quis rutrum varius, nunc dui convallis purus, non maximus risus orci nec nisl. Vivamus convallis congue purus, a venenatis est finibus sed.

Mauris quis consequat ante. Sed iaculis nibh id sem imperdiet suscipit. Sed fermentum eleifend lorem, at ornare tortor gravida non. Donec aliquam mauris ligula, et dictum diam rutrum sit amet. In tincidunt, metus non interdum gravida, leo eros ultrices purus, a maximus dui mi vel dui. Integer rutrum elit ut tortor tempus maximus. Phasellus consequat eleifend nunc ac fringilla. Maecenas ac dictum eros. Proin vulputate laoreet dolor sed pulvinar. Nulla iaculis a purus sed luctus. Praesent vehicula erat a magna scelerisque, sed pulvinar ipsum luctus. Vestibulum in feugiat neque. Ut pellentesque ante nec tellus volutpat pretium. Quisque id tempor mi.

Phasellus scelerisque sapien turpis, finibus imperdiet nunc suscipit vel. Suspendisse non lectus in mi laoreet euismod. Fusce at elit nec ipsum consectetur fringilla. Nunc in ex finibus, pretium ex aliquam, tristique eros. Fusce eget fermentum nisi, a luctus tortor. Quisque gravida imperdiet lorem, vitae vestibulum lorem vestibulum ut. Vestibulum eu elit risus. Integer eu nulla fermentum, vestibulum velit id, finibus risus. Ut a odio consequat, scelerisque ligula at, dignissim arcu. Aenean interdum mauris tincidunt, feugiat tortor ac, fringilla risus. Vivamus id convallis massa. Pellentesque in justo vel justo egestas fringilla at vel turpis.

Mauris in eros quis est gravida fermentum. Sed in finibus elit. Aliquam faucibus interdum purus, nec hendrerit elit pretium at. Maecenas in euismod quam, sed tin 
    </MDBContainer>
    )
    };
}

export default Body;